export const SUBSCRIBE_TO_NOTIFICATION = 'SUBSCRIBE_TO_NOTIFICATION';
export const SUBSCRIPTION_SUCCEED = 'SUBSCRIPTION_SUCCEED';
export const SUBSCRIPTION_FAILED = 'SUBSCRIPTION_FAILED';


export const BROADCAST_MESSAGE = 'BROADCAST_MESSAGE';
export const BROADCAST_SUCCEED = 'BROADCAST_SUCCEED';
export const BROADCAST_FAILED = 'BROADCAST_FAILED';
